CREATE TABLE T_PURCHASE_JDSTORE
(
  ID              NUMBER(10) not null,
  CLIENT_NAME     VARCHAR2(50),
  IDCARD      VARCHAR2(20),
  TEL      VARCHAR2(15),
  PRODUCT_TYPE     VARCHAR2(20),
  ORDER_NO     VARCHAR2(20),
  ORDER_STATUS    VARCHAR2(20),
  ORDER_AMOUNT DECIMAL(10,2),
  PAY_TIME    DATE,
  STORE_ID VARCHAR2(10),
  SIGNED_USER  VARCHAR2(100),
  CONTRACT_NO   VARCHAR2(50),
  CAR_TYPE VARCHAR2(20),
  CAR_VIN  VARCHAR2(20),
  CREATE_USER NUMBER(10),
  CREATE_DATE DATE,
  UPDATE_USER NUMBER(10),
  UPDATE_DATE DATE
);

COMMENT ON TABLE T_PURCHASE_JDSTORE IS '京东店铺交易明细表';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.ID IS 'ID';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.CLIENT_NAME IS '客户名称';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.IDCARD IS '身份证号';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.TEL IS '手机号';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.PRODUCT_TYPE IS '活动产品类型';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.ORDER_NO IS '订单号';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.ORDER_STATUS IS '订单状态';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.ORDER_AMOUNT IS '订单金额';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.PAY_TIME IS '支付时间';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.STORE_ID IS '门店ID';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.SIGNED_USER IS '签署对象';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.CONTRACT_NO IS '合同号';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.CAR_TYPE IS '车型';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.CAR_VIN IS '车架号';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.CREATE_USER IS '录入人';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.CREATE_DATE IS '录入时间';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.UPDATE_USER IS '修改人';
COMMENT ON COLUMN T_PURCHASE_JDSTORE.UPDATE_DATE IS '修改时间';

alter table T_PURCHASE_JDSTORE add constraint PK_PURCHASE_JDSTORE primary key (ID);
create sequence S_PURCHASE_JDSTORE;