CREATE TABLE LM_TASK_SCORE
(
  ID             NUMBER(10),
  CLIENT_ID      NUMBER(10),
  USER_ID        NUMBER(10),
  MONTH          VARCHAR2(10 BYTE),
  OVERTIME_TYPE  VARCHAR2(2 BYTE),
  SCORE          NUMBER(3),
  SCORE_TYPE     VARCHAR2(2 BYTE),
  CREATE_DATE    DATE                           DEFAULT sysdate
);

COMMENT ON TABLE LM_TASK_SCORE IS '任务积分表';

COMMENT ON COLUMN LM_TASK_SCORE.ID IS '数据ID';

COMMENT ON COLUMN LM_TASK_SCORE.CLIENT_ID IS '线索ID';

COMMENT ON COLUMN LM_TASK_SCORE.USER_ID IS '用户ID';

COMMENT ON COLUMN LM_TASK_SCORE.MONTH IS '年月（yyyy-mm）';

COMMENT ON COLUMN LM_TASK_SCORE.OVERTIME_TYPE IS '超时类型 1:24小时  2:96小时  3:192小时';

COMMENT ON COLUMN LM_TASK_SCORE.SCORE IS '积分';

COMMENT ON COLUMN LM_TASK_SCORE.SCORE_TYPE IS '扣分类型 1减分 2加分(弃单转成单)';

COMMENT ON COLUMN LM_TASK_SCORE.CREATE_DATE IS '创建时间';



CREATE UNIQUE INDEX PK_LM_TASK_SCORE ON LM_TASK_SCORE
(ID);


ALTER TABLE LM_TASK_SCORE ADD (
  CONSTRAINT PK_LM_TASK_SCORE
  PRIMARY KEY
  (ID)
  USING INDEX PK_LM_TASK_SCORE
  ENABLE VALIDATE);
