CREATE TABLE LM_URGE
(
  ID                      NUMBER(10)            NOT NULL,
  URGE_AFFAIR_ID          VARCHAR2(20 BYTE),
  URGE_AFFAIR_CONTENT     VARCHAR2(500 BYTE),
  URGE_FIRST_PERSON_ID    NUMBER(10),
  URGE_FIRST_ORGAN_ID     VARCHAR2(10 BYTE),
  URGE_FIRST_PERSON_NAME  VARCHAR2(100 BYTE),
  URGE_PERSON_ID          NUMBER(10),
  URGE_ORGAN_ID           VARCHAR2(10 BYTE),
  URGE_PERSON_NAME        VARCHAR2(100 BYTE),
  URGE_TO_PERSON_ID       NUMBER(10),
  URGE_TO_ORGAN_ID        VARCHAR2(10 BYTE),
  URGE_TO_PERSON_NAME     VARCHAR2(100 BYTE),
  URGE_UPDATE_DATE        DATE,
  URGE_NUM                NUMBER(10),
  URGE_CREATE_DATE        DATE,
  URGE_END_DATE           DATE,
  URGE_STATUS             VARCHAR2(2 BYTE)
);

COMMENT ON COLUMN LM_URGE.ID IS '主键';

COMMENT ON COLUMN LM_URGE.URGE_AFFAIR_ID IS '催促事件ID  （线索ID）';

COMMENT ON COLUMN LM_URGE.URGE_AFFAIR_CONTENT IS '催促事件内容';

COMMENT ON COLUMN LM_URGE.URGE_FIRST_PERSON_ID IS '第一次催促人ID';

COMMENT ON COLUMN LM_URGE.URGE_FIRST_ORGAN_ID IS '第一次催促人组织';

COMMENT ON COLUMN LM_URGE.URGE_FIRST_PERSON_NAME IS '第一次催促人姓名';

COMMENT ON COLUMN LM_URGE.URGE_PERSON_ID IS '催促人ID';

COMMENT ON COLUMN LM_URGE.URGE_ORGAN_ID IS '催促人组织';

COMMENT ON COLUMN LM_URGE.URGE_PERSON_NAME IS '催促人姓名';

COMMENT ON COLUMN LM_URGE.URGE_TO_PERSON_ID IS '被催促人ID';

COMMENT ON COLUMN LM_URGE.URGE_TO_ORGAN_ID IS '被催促人组织';

COMMENT ON COLUMN LM_URGE.URGE_TO_PERSON_NAME IS '被催促人姓名';

COMMENT ON COLUMN LM_URGE.URGE_UPDATE_DATE IS '催促修改事件，多次催促仅仅修改这个时间';

COMMENT ON COLUMN LM_URGE.URGE_NUM IS '催促次数';

COMMENT ON COLUMN LM_URGE.URGE_CREATE_DATE IS '催促时间';

COMMENT ON COLUMN LM_URGE.URGE_END_DATE IS '催促事件结束时间';

COMMENT ON COLUMN LM_URGE.URGE_STATUS IS '催促状态，0为未办 1已办';



CREATE UNIQUE INDEX URGE ON LM_URGE
(ID);


ALTER TABLE LM_URGE ADD (
  CONSTRAINT URGE
  PRIMARY KEY
  (ID)
  USING INDEX URGE
  ENABLE VALIDATE);
