CREATE TABLE T_BASE_CITY
(
  ID          NUMBER(10)                        NOT NULL,
  CITY_CODE   VARCHAR2(10 BYTE)                 NOT NULL,
  CITY_NAME   VARCHAR2(50 BYTE),
  ABBR_NAME   VARCHAR2(50 BYTE),
  RANK_ID     VARCHAR2(10 BYTE)                 NOT NULL,
  RANK_PID    VARCHAR2(10 BYTE)                 NOT NULL,
  STATUS      VARCHAR2(2 BYTE),
  FULL_NAME   VARCHAR2(60 BYTE),
  CITY_RANK   VARCHAR2(2 BYTE),
  CITY_LEVEL  VARCHAR2(2 BYTE)
);

COMMENT ON COLUMN T_BASE_CITY.ID IS '数据ID';

COMMENT ON COLUMN T_BASE_CITY.CITY_CODE IS '市城CODE';

COMMENT ON COLUMN T_BASE_CITY.CITY_NAME IS '市城名称';

COMMENT ON COLUMN T_BASE_CITY.ABBR_NAME IS '市城名称（简写）';

COMMENT ON COLUMN T_BASE_CITY.RANK_ID IS '阶层 ID';

COMMENT ON COLUMN T_BASE_CITY.RANK_PID IS '阶层 PID';

COMMENT ON COLUMN T_BASE_CITY.STATUS IS '是否启用，0为禁用，1为启用';

COMMENT ON COLUMN T_BASE_CITY.FULL_NAME IS '全名';

COMMENT ON COLUMN T_BASE_CITY.CITY_RANK IS '0-国家，1-省，2-市，3-区县，4-乡镇';

COMMENT ON COLUMN T_BASE_CITY.CITY_LEVEL IS '区分城市是一线还是二线';
