CREATE TABLE T_CODE_ITEM
(
  CODE_TYPE     VARCHAR2(10 BYTE),
  NAME          VARCHAR2(200 BYTE),
  VALUE         VARCHAR2(200 BYTE),
  SEQ           NUMBER(9),
  STATUS        VARCHAR2(2 BYTE)                DEFAULT 1,
  CREATE_DATE   DATE                            DEFAULT sysdate,
  ASSISTANT     VARCHAR2(200 BYTE),
  CODE_ITEM_ID  NUMBER(10)
);

COMMENT ON TABLE T_CODE_ITEM IS '码表明细';

COMMENT ON COLUMN T_CODE_ITEM.CODE_TYPE IS '类型';

COMMENT ON COLUMN T_CODE_ITEM.NAME IS '名称';

COMMENT ON COLUMN T_CODE_ITEM.VALUE IS '值';

COMMENT ON COLUMN T_CODE_ITEM.SEQ IS '序号';

COMMENT ON COLUMN T_CODE_ITEM.STATUS IS '状态 0失效';

COMMENT ON COLUMN T_CODE_ITEM.ASSISTANT IS '辅助字段';

COMMENT ON COLUMN T_CODE_ITEM.CODE_ITEM_ID IS '主键';



CREATE UNIQUE INDEX IDX_CODE_ITEM_ID ON T_CODE_ITEM
(CODE_ITEM_ID);


CREATE INDEX IDX_CODE_TYPE ON T_CODE_ITEM
(CODE_TYPE);


ALTER TABLE T_CODE_ITEM ADD (
  CONSTRAINT CODE_ITEM_ID
  PRIMARY KEY
  (CODE_ITEM_ID)
  DISABLE NOVALIDATE);
