CREATE TABLE T_COUPON_PARTNER
(
  ID               NUMBER(10)                   NOT NULL,
  PARTNER_CODE     VARCHAR2(20 BYTE),
  PARTNER_NAME     VARCHAR2(60 BYTE),
  PROVINCE         NUMBER(10),
  CITY             NUMBER(10),
  ADDRESS          VARCHAR2(100 BYTE),
  CONTACT          VARCHAR2(20 BYTE),
  TEL              VARCHAR2(20 BYTE),
  SERVICE          VARCHAR2(100 BYTE),
  CREATED_TIME     DATE                         DEFAULT SYSDATE,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE                         DEFAULT SYSDATE,
  UPDATED_USER_ID  NUMBER(10),
  REMARK           VARCHAR2(100 BYTE)
);

COMMENT ON TABLE T_COUPON_PARTNER IS '合作商';

COMMENT ON COLUMN T_COUPON_PARTNER.ID IS '数据ID';

COMMENT ON COLUMN T_COUPON_PARTNER.PARTNER_CODE IS '合作商编号';

COMMENT ON COLUMN T_COUPON_PARTNER.PARTNER_NAME IS '合作商名称';

COMMENT ON COLUMN T_COUPON_PARTNER.PROVINCE IS '所在省';

COMMENT ON COLUMN T_COUPON_PARTNER.CITY IS '所在市';

COMMENT ON COLUMN T_COUPON_PARTNER.ADDRESS IS '详细地址';

COMMENT ON COLUMN T_COUPON_PARTNER.CONTACT IS '联系人';

COMMENT ON COLUMN T_COUPON_PARTNER.TEL IS '联系电话';

COMMENT ON COLUMN T_COUPON_PARTNER.SERVICE IS '服务内容';

COMMENT ON COLUMN T_COUPON_PARTNER.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN T_COUPON_PARTNER.CREATED_USER_ID IS '创建人ID';

COMMENT ON COLUMN T_COUPON_PARTNER.UPDATED_TIME IS '更新时间';

COMMENT ON COLUMN T_COUPON_PARTNER.UPDATED_USER_ID IS '更新人ID';

COMMENT ON COLUMN T_COUPON_PARTNER.REMARK IS '备注';



CREATE UNIQUE INDEX PK_T_COUPON_PARTNER ON T_COUPON_PARTNER
(ID);


ALTER TABLE T_COUPON_PARTNER ADD (
  CONSTRAINT PK_T_COUPON_PARTNER
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_COUPON_PARTNER
  ENABLE VALIDATE);
