CREATE TABLE T_HOLIDAY
(
  ID            NUMBER(10)                      NOT NULL,
  HOLIDAY       DATE,
  HOLIDAY_TYPE  VARCHAR2(2 BYTE),
  CREATE_DATE   DATE                            DEFAULT sysdate,
  CREATE_USER   NUMBER(10),
  MODIFY_DATE   DATE,
  MODIFY_USER   NUMBER(10)
);

COMMENT ON TABLE T_HOLIDAY IS '节假日信息表';

COMMENT ON COLUMN T_HOLIDAY.ID IS '数据ID';

COMMENT ON COLUMN T_HOLIDAY.HOLIDAY IS '节假日(yyyy-mm-dd)';

COMMENT ON COLUMN T_HOLIDAY.HOLIDAY_TYPE IS '节假日类型 1:假日 2:节日 3:自定义';

COMMENT ON COLUMN T_HOLIDAY.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN T_HOLIDAY.CREATE_USER IS '创建人ID';

COMMENT ON COLUMN T_HOLIDAY.MODIFY_DATE IS '修改日期';

COMMENT ON COLUMN T_HOLIDAY.MODIFY_USER IS '修改人ID';



CREATE UNIQUE INDEX PK_T_HOLIDAY ON T_HOLIDAY
(ID);


ALTER TABLE T_HOLIDAY ADD (
  CONSTRAINT PK_T_HOLIDAY
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_HOLIDAY
  ENABLE VALIDATE);
