CREATE TABLE T_MODULE_GROUP
(
  GROUP_ID     NUMBER(10)                       NOT NULL,
  GROUP_NAME   VARCHAR2(200 BYTE)               NOT NULL,
  GROUP_ORDER  NUMBER(10)                       DEFAULT 0,
  REMARK       VARCHAR2(500 BYTE),
  CREATE_DATE  DATE                             DEFAULT sysdate
);


CREATE UNIQUE INDEX PK_MODULE_GROUP_ID ON T_MODULE_GROUP
(GROUP_ID);


ALTER TABLE T_MODULE_GROUP ADD (
  CONSTRAINT PK_MODULE_GROUP_ID
  PRIMARY KEY
  (GROUP_ID)
  USING INDEX PK_MODULE_GROUP_ID
  ENABLE VALIDATE);
