CREATE TABLE T_MODULE_GROUP_URL
(
  GROUP_ID   NUMBER(10)                         NOT NULL,
  MODULE_ID  NUMBER(10)                         NOT NULL,
  SEQ        NUMBER(10)                         NOT NULL
);

COMMENT ON TABLE T_MODULE_GROUP_URL IS '组菜单';

COMMENT ON COLUMN T_MODULE_GROUP_URL.GROUP_ID IS '组id';

COMMENT ON COLUMN T_MODULE_GROUP_URL.MODULE_ID IS 'url的id';

COMMENT ON COLUMN T_MODULE_GROUP_URL.SEQ IS '显示序号 ';



ALTER TABLE T_MODULE_GROUP_URL ADD (
  CONSTRAINT FK_GROUP_ID 
  FOREIGN KEY (GROUP_ID) 
  REFERENCES T_MODULE_GROUP (GROUP_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_MODULE_ID 
  FOREIGN KEY (MODULE_ID) 
  REFERENCES T_MODULE_URL (MODULE_ID)
  ENABLE VALIDATE);
