CREATE TABLE T_QA_DETAIL
(
  ID               NUMBER(10)                   NOT NULL,
  PID              NUMBER(10),
  QUESTION         VARCHAR2(100 BYTE),
  ANSWER           VARCHAR2(1000 BYTE),
  FILE_NAME        VARCHAR2(100 BYTE),
  FILE_PATH        VARCHAR2(255 BYTE),
  STATUS           VARCHAR2(5 BYTE)             DEFAULT '1',
  CREATED_TIME     DATE                         DEFAULT SYSDATE,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE                         DEFAULT SYSDATE,
  UPDATED_USER_ID  NUMBER(10)
);

COMMENT ON TABLE T_QA_DETAIL IS '知识库详情表';

COMMENT ON COLUMN T_QA_DETAIL.ID IS '数据ID';

COMMENT ON COLUMN T_QA_DETAIL.PID IS '主表ID';

COMMENT ON COLUMN T_QA_DETAIL.QUESTION IS '问题';

COMMENT ON COLUMN T_QA_DETAIL.ANSWER IS '答案';

COMMENT ON COLUMN T_QA_DETAIL.FILE_NAME IS '附件名称';

COMMENT ON COLUMN T_QA_DETAIL.FILE_PATH IS '附件path';

COMMENT ON COLUMN T_QA_DETAIL.STATUS IS '状态';

COMMENT ON COLUMN T_QA_DETAIL.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN T_QA_DETAIL.CREATED_USER_ID IS '创建人ID';

COMMENT ON COLUMN T_QA_DETAIL.UPDATED_TIME IS '更新时间';

COMMENT ON COLUMN T_QA_DETAIL.UPDATED_USER_ID IS '更新人ID';



CREATE UNIQUE INDEX PK_T_QA_DETAIL ON T_QA_DETAIL
(ID);


ALTER TABLE T_QA_DETAIL ADD (
  CONSTRAINT PK_T_QA_DETAIL
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_QA_DETAIL
  ENABLE VALIDATE);
