CREATE TABLE T_USER
(
  USER_ID      NUMBER(10)                       NOT NULL,
  USER_CODE    VARCHAR2(32 BYTE)                NOT NULL,
  USER_NAME    VARCHAR2(50 BYTE),
  REAL_NAME    VARCHAR2(50 BYTE),
  JZ_CODE      VARCHAR2(20 BYTE),
  ORGAN_ID     VARCHAR2(20 BYTE)                NOT NULL,
  PASSWORD     VARCHAR2(100 BYTE),
  STATUS       VARCHAR2(2 BYTE)                 DEFAULT 1,
  CREATE_DATE  DATE                             DEFAULT sysdate,
  ORGAN_CODE   VARCHAR2(20 BYTE),
  ROLE         VARCHAR2(20 BYTE)                DEFAULT 'ROLE_USER',
  TEL          VARCHAR2(32 BYTE),
  EMAIL        VARCHAR2(32 BYTE),
  ISPASS       VARCHAR2(2 BYTE)                 DEFAULT 0
);

COMMENT ON TABLE T_USER IS '用户表';

COMMENT ON COLUMN T_USER.STATUS IS '0失效';

COMMENT ON COLUMN T_USER.ORGAN_CODE IS '组织代码 JZ JY';

COMMENT ON COLUMN T_USER.TEL IS '电话';

COMMENT ON COLUMN T_USER.EMAIL IS '电子邮箱';

COMMENT ON COLUMN T_USER.ISPASS IS '是否修改过密码：1 表示已修改，控制用户登录后必须进行密码修改.';



CREATE UNIQUE INDEX PK_USER_USER_ID ON T_USER
(USER_ID);


ALTER TABLE T_USER ADD (
  CONSTRAINT PK_USER_USER_ID
  PRIMARY KEY
  (USER_ID)
  USING INDEX PK_USER_USER_ID
  ENABLE VALIDATE);
