CREATE TABLE T_USER_LOGIN
(
  ID            NUMBER(10)                      NOT NULL,
  USER_ID       NUMBER(10),
  USER_CODE     VARCHAR2(40 BYTE),
  LOGIN_IP      VARCHAR2(40 BYTE),
  EXPIRED       VARCHAR2(2 BYTE)                DEFAULT 0,
  LOGIN_DATE    DATE                            DEFAULT sysdate,
  LOGOUT_DATE   DATE,
  UUID          VARCHAR2(500 BYTE),
  SESSION_ID    VARCHAR2(100 BYTE),
  LAST_REQUEST  DATE                            DEFAULT sysdate
);

COMMENT ON COLUMN T_USER_LOGIN.EXPIRED IS '�Ƿ�ʧЧ 1ʧЧ';



CREATE INDEX IDX_ORGPERSON_LOGIN ON T_USER_LOGIN
(USER_ID, EXPIRED);


CREATE INDEX IDX_USER_LOGIN_SESSIONID ON T_USER_LOGIN
(SESSION_ID);


CREATE INDEX IDX_USER_LOGIN_UUID ON T_USER_LOGIN
(UUID);
