CREATE TABLE T_WEIXIN_MAIN
(
  ID            NUMBER                          NOT NULL,
  CORP_ID       VARCHAR2(50 BYTE)               NOT NULL,
  NAME          VARCHAR2(150 BYTE),
  PROJECT_URL   VARCHAR2(250 BYTE),
  PROJECT_NAME  VARCHAR2(250 BYTE)
);

COMMENT ON TABLE T_WEIXIN_MAIN IS '微信企业号';

COMMENT ON COLUMN T_WEIXIN_MAIN.CORP_ID IS '企业号ID';

COMMENT ON COLUMN T_WEIXIN_MAIN.NAME IS '名称';



CREATE UNIQUE INDEX PK_WEIXIN_MAIN_ID ON T_WEIXIN_MAIN
(ID);


ALTER TABLE T_WEIXIN_MAIN ADD (
  CONSTRAINT PK_WEIXIN_MAIN_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_WEIXIN_MAIN_ID
  ENABLE VALIDATE);
