CREATE TABLE T_WEIXIN_USER
(
  ID           NUMBER(10)                       NOT NULL,
  JZ_CODE      VARCHAR2(20 BYTE),
  NAME         VARCHAR2(50 BYTE),
  STATUS       VARCHAR2(2 BYTE)                 DEFAULT 1,
  CREATE_DATE  DATE                             DEFAULT sysdate
);

COMMENT ON TABLE T_WEIXIN_USER IS '企业号用户';

COMMENT ON COLUMN T_WEIXIN_USER.ID IS 'id';

COMMENT ON COLUMN T_WEIXIN_USER.JZ_CODE IS '员工唯一标识 JZ000001';

COMMENT ON COLUMN T_WEIXIN_USER.NAME IS '姓名';

COMMENT ON COLUMN T_WEIXIN_USER.STATUS IS '状态 1有效';

COMMENT ON COLUMN T_WEIXIN_USER.CREATE_DATE IS '创建时间';



CREATE INDEX IDX_WX_USER_CODE ON T_WEIXIN_USER
(JZ_CODE);


CREATE UNIQUE INDEX PK_WEIXIN_USER_ID ON T_WEIXIN_USER
(ID);


ALTER TABLE T_WEIXIN_USER ADD (
  CONSTRAINT PK_WEIXIN_USER_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_WEIXIN_USER_ID
  ENABLE VALIDATE);
