CREATE TABLE T_WEIXIN_USER_AGENT
(
  WX_USER_ID  NUMBER(10)                        NOT NULL,
  AGENT_ID    VARCHAR2(10 BYTE)                 NOT NULL,
  AGENT_NAME  VARCHAR2(100 BYTE),
  USER_CODE   VARCHAR2(50 BYTE)                 NOT NULL,
  ID          NUMBER(10)                        NOT NULL
);

COMMENT ON TABLE T_WEIXIN_USER_AGENT IS '企业号员工所拥有的应用';

COMMENT ON COLUMN T_WEIXIN_USER_AGENT.WX_USER_ID IS '主表ID';

COMMENT ON COLUMN T_WEIXIN_USER_AGENT.AGENT_ID IS '应用ID';

COMMENT ON COLUMN T_WEIXIN_USER_AGENT.AGENT_NAME IS '应用名称';

COMMENT ON COLUMN T_WEIXIN_USER_AGENT.USER_CODE IS '应用对应系统user_code 登录工号';

COMMENT ON COLUMN T_WEIXIN_USER_AGENT.ID IS 'id';



CREATE UNIQUE INDEX PK_USER_AGENT_ID ON T_WEIXIN_USER_AGENT
(ID);


ALTER TABLE T_WEIXIN_USER_AGENT ADD (
  CONSTRAINT PK_USER_AGENT_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_USER_AGENT_ID
  ENABLE VALIDATE);
