CREATE TABLE LINK_ERP_REPORT
(
  ID             NUMBER(10)                     NOT NULL,
  CLIENT_ID      NUMBER(10),
  L_NAME         VARCHAR2(250 BYTE),
  L_TEL_PHONE    VARCHAR2(20 BYTE),
  L_CREATE_TIME  DATE,
  L_PRO_CODE     VARCHAR2(60 BYTE),
  L_CATENA_NAME  VARCHAR2(250 BYTE),
  L_SPEC_NAME    VARCHAR2(250 BYTE),
  L_SCHEME_NAME  VARCHAR2(550 BYTE),
  CREATE_TIME    DATE                           DEFAULT sysdate,
  DB_SOURCE      VARCHAR2(2 BYTE)
);

COMMENT ON COLUMN LINK_ERP_REPORT.ID IS '数据ID';

COMMENT ON COLUMN LINK_ERP_REPORT.CLIENT_ID IS '线索ID';

COMMENT ON COLUMN LINK_ERP_REPORT.L_NAME IS '客户名称';

COMMENT ON COLUMN LINK_ERP_REPORT.L_TEL_PHONE IS '手机号';

COMMENT ON COLUMN LINK_ERP_REPORT.L_CREATE_TIME IS '成交时间';

COMMENT ON COLUMN LINK_ERP_REPORT.L_PRO_CODE IS '项目编号';

COMMENT ON COLUMN LINK_ERP_REPORT.L_CATENA_NAME IS '系别名称';

COMMENT ON COLUMN LINK_ERP_REPORT.L_SPEC_NAME IS '型号名称';

COMMENT ON COLUMN LINK_ERP_REPORT.L_SCHEME_NAME IS '商务政策别名';

COMMENT ON COLUMN LINK_ERP_REPORT.CREATE_TIME IS '数据创建时间';

COMMENT ON COLUMN LINK_ERP_REPORT.DB_SOURCE IS '数据来源 22:捷众 24:结义';



CREATE UNIQUE INDEX PK_LINK_ERP_REPORT ON LINK_ERP_REPORT
(ID);


ALTER TABLE LINK_ERP_REPORT ADD (
  CONSTRAINT PK_LINK_ERP_REPORT
  PRIMARY KEY
  (ID)
  USING INDEX PK_LINK_ERP_REPORT
  ENABLE VALIDATE);
