CREATE TABLE LM_ALLCATION_ITEM
(
  ID                  NUMBER(10),
  ALLOCATION_TIME     DATE                      DEFAULT sysdate,
  USER_ID             NUMBER(10),
  ALLOCATION_USER_ID  NUMBER(10),
  CLIENT_ID           NUMBER(10)
);

COMMENT ON COLUMN LM_ALLCATION_ITEM.ID IS '主键';

COMMENT ON COLUMN LM_ALLCATION_ITEM.ALLOCATION_TIME IS '分配时间';

COMMENT ON COLUMN LM_ALLCATION_ITEM.USER_ID IS '被分配人ID';

COMMENT ON COLUMN LM_ALLCATION_ITEM.ALLOCATION_USER_ID IS '分配人ID';

COMMENT ON COLUMN LM_ALLCATION_ITEM.CLIENT_ID IS '线索ID';



CREATE UNIQUE INDEX PK_ALLOCATION_ITEM_ID ON LM_ALLCATION_ITEM
(ID);


ALTER TABLE LM_ALLCATION_ITEM ADD (
  CONSTRAINT PK_ALLOCATION_ITEM_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_ALLOCATION_ITEM_ID
  ENABLE VALIDATE);
