CREATE TABLE LM_CLIENT_UPDATE
(
  ID               NUMBER(10)                   NOT NULL,
  CLIENT_ID        NUMBER(10),
  FIELD            VARCHAR2(50 BYTE),
  FIELD_BEFORE     VARCHAR2(200 BYTE),
  FIELD_AFTER      VARCHAR2(200 BYTE),
  UPDATE_INDEX     VARCHAR2(50 BYTE),
  CREATED_TIME     DATE                         DEFAULT sysdate,
  CREATED_USER_ID  NUMBER(10)
);

COMMENT ON TABLE LM_CLIENT_UPDATE IS '线索主表更改跟踪';

COMMENT ON COLUMN LM_CLIENT_UPDATE.ID IS '数据主键';

COMMENT ON COLUMN LM_CLIENT_UPDATE.CLIENT_ID IS '线索ID';

COMMENT ON COLUMN LM_CLIENT_UPDATE.FIELD IS '字段名称';

COMMENT ON COLUMN LM_CLIENT_UPDATE.FIELD_BEFORE IS '字段改变前值';

COMMENT ON COLUMN LM_CLIENT_UPDATE.FIELD_AFTER IS '字段改变后值';

COMMENT ON COLUMN LM_CLIENT_UPDATE.UPDATE_INDEX IS '更改序列';

COMMENT ON COLUMN LM_CLIENT_UPDATE.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN LM_CLIENT_UPDATE.CREATED_USER_ID IS '创建人';



CREATE UNIQUE INDEX PK_T_CLIENT_UPDATE ON LM_CLIENT_UPDATE
(ID);


ALTER TABLE LM_CLIENT_UPDATE ADD (
  CONSTRAINT PK_T_CLIENT_UPDATE
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_CLIENT_UPDATE
  ENABLE VALIDATE);
