CREATE TABLE LM_PRODUCT
(
  ID         NUMBER(20)                         NOT NULL,
  ABNAME     VARCHAR2(50 BYTE),
  PNAME      VARCHAR2(100 BYTE),
  PDESCRIBE  VARCHAR2(1000 BYTE),
  PDETAIL    VARCHAR2(3000 BYTE),
  PID        NUMBER(20),
  HAS_CHILD  VARCHAR2(5 BYTE),
  ROLES      VARCHAR2(50 BYTE)
);

COMMENT ON TABLE LM_PRODUCT IS '产品内容';

COMMENT ON COLUMN LM_PRODUCT.ABNAME IS '产品简称';

COMMENT ON COLUMN LM_PRODUCT.PNAME IS '产品名称';

COMMENT ON COLUMN LM_PRODUCT.PDESCRIBE IS '产品介绍';

COMMENT ON COLUMN LM_PRODUCT.PDETAIL IS '话术';



CREATE UNIQUE INDEX PK_LM_PRODUCT ON LM_PRODUCT
(ID);


ALTER TABLE LM_PRODUCT ADD (
  CONSTRAINT PK_LM_PRODUCT
  PRIMARY KEY
  (ID)
  USING INDEX PK_LM_PRODUCT
  ENABLE VALIDATE);
