CREATE TABLE LM_PLAN_SCORE_STATE
(
  ID           NUMBER(10),
  USER_ID      VARCHAR2(20 BYTE),
  CLIENT_ID    VARCHAR2(20 BYTE),
  MONTH        VARCHAR2(10 BYTE),
  PLAN_STATE   CHAR(1 BYTE),
  SCORE_STATE  CHAR(1 BYTE),
  CREATE_DATE  DATE                             DEFAULT sysdate
);

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.ID IS 'ID';

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.USER_ID IS '销售ID';

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.CLIENT_ID IS '线索ID';

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.MONTH IS '月份';

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.PLAN_STATE IS '任务状态 0 未处理 1已处理';

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.SCORE_STATE IS '加分状态 0 未处理 1已处理';

COMMENT ON COLUMN LM_PLAN_SCORE_STATE.CREATE_DATE IS '创建时间';
