CREATE TABLE LM_TIMEOUT_TASK
(
  ID             NUMBER(10)                     NOT NULL,
  CLIENT_ID      NUMBER(10)                     NOT NULL,
  MONTH          VARCHAR2(10 BYTE),
  OVERTIME_TYPE  VARCHAR2(10 BYTE),
  STATUS         VARCHAR2(2 BYTE)               DEFAULT 0,
  CREATE_DATE    DATE                           DEFAULT sysdate,
  USER_ID        NUMBER(10),
  CLIENT_NAME    VARCHAR2(300 BYTE),
  BUSINESS_TYPE  VARCHAR2(100 BYTE),
  TEL            VARCHAR2(20 BYTE),
  ALLOTDATE      DATE
);

COMMENT ON TABLE LM_TIMEOUT_TASK IS '超时任务列表';

COMMENT ON COLUMN LM_TIMEOUT_TASK.ID IS '数据ID';

COMMENT ON COLUMN LM_TIMEOUT_TASK.CLIENT_ID IS '线索表ID';

COMMENT ON COLUMN LM_TIMEOUT_TASK.MONTH IS '年月(yyyy-mm)';

COMMENT ON COLUMN LM_TIMEOUT_TASK.OVERTIME_TYPE IS '超时类型 1:24小时  2:96小时 3:192小时';

COMMENT ON COLUMN LM_TIMEOUT_TASK.STATUS IS '处理状态 0:未处理 1:已处理';

COMMENT ON COLUMN LM_TIMEOUT_TASK.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN LM_TIMEOUT_TASK.USER_ID IS '销售人员ID';

COMMENT ON COLUMN LM_TIMEOUT_TASK.CLIENT_NAME IS '联系人';

COMMENT ON COLUMN LM_TIMEOUT_TASK.BUSINESS_TYPE IS '业务类型';

COMMENT ON COLUMN LM_TIMEOUT_TASK.TEL IS '联系电话';

COMMENT ON COLUMN LM_TIMEOUT_TASK.ALLOTDATE IS '线索分配时间';



CREATE UNIQUE INDEX PK_LM_TIMEOUT_TASK ON LM_TIMEOUT_TASK
(ID);


ALTER TABLE LM_TIMEOUT_TASK ADD (
  CONSTRAINT PK_LM_TIMEOUT_TASK
  PRIMARY KEY
  (ID)
  USING INDEX PK_LM_TIMEOUT_TASK
  ENABLE VALIDATE);
