CREATE TABLE SMS_SEND_INFO
(
  ID               NUMBER(10)                   NOT NULL,
  SEND_USER_ID     NUMBER(10),
  RE_NAME          VARCHAR2(50 BYTE),
  RE_TEL           VARCHAR2(50 BYTE),
  STORE_ADDRESS    VARCHAR2(1000 BYTE),
  MSG              VARCHAR2(1000 BYTE),
  STATUS           VARCHAR2(5 BYTE),
  STATUS_DES       VARCHAR2(200 BYTE),
  CREATED_TIME     DATE                         DEFAULT sysdate,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE,
  UPDATED_USER_ID  NUMBER(10),
  CLIENT_ID        NUMBER(10),
  SMS_TYPE         VARCHAR2(5 BYTE)
);

COMMENT ON TABLE SMS_SEND_INFO IS '短信信息记录';

COMMENT ON COLUMN SMS_SEND_INFO.ID IS '数据ID';

COMMENT ON COLUMN SMS_SEND_INFO.SEND_USER_ID IS '发送人ID';

COMMENT ON COLUMN SMS_SEND_INFO.RE_NAME IS '接收人姓名';

COMMENT ON COLUMN SMS_SEND_INFO.RE_TEL IS '接收人电话';

COMMENT ON COLUMN SMS_SEND_INFO.STORE_ADDRESS IS '门店地址';

COMMENT ON COLUMN SMS_SEND_INFO.MSG IS '短信内容';

COMMENT ON COLUMN SMS_SEND_INFO.STATUS IS '状态';

COMMENT ON COLUMN SMS_SEND_INFO.STATUS_DES IS '状态描述';

COMMENT ON COLUMN SMS_SEND_INFO.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN SMS_SEND_INFO.CREATED_USER_ID IS '创建人';

COMMENT ON COLUMN SMS_SEND_INFO.UPDATED_TIME IS '更新时间';

COMMENT ON COLUMN SMS_SEND_INFO.UPDATED_USER_ID IS '更新人ID';

COMMENT ON COLUMN SMS_SEND_INFO.CLIENT_ID IS '线索ID';



CREATE INDEX IND_SMS_TEL ON SMS_SEND_INFO
(RE_TEL);


CREATE UNIQUE INDEX PK_SMS_SEND_INFO ON SMS_SEND_INFO
(ID);


ALTER TABLE SMS_SEND_INFO ADD (
  CONSTRAINT PK_SMS_SEND_INFO
  PRIMARY KEY
  (ID)
  USING INDEX PK_SMS_SEND_INFO
  ENABLE VALIDATE);
