CREATE TABLE SMS_TEMPLATE
(
  ID               NUMBER(10)                   NOT NULL,
  CONTENT          VARCHAR2(1000 BYTE),
  TYPE             VARCHAR2(10 BYTE),
  PARAMS_NUM       VARCHAR2(10 BYTE),
  STATUS           VARCHAR2(5 BYTE),
  REMARK           VARCHAR2(200 BYTE),
  CREATED_TIME     DATE                         DEFAULT sysdate,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE,
  UPDATED_USER_ID  NUMBER(10)
);

COMMENT ON TABLE SMS_TEMPLATE IS '短信模板';

COMMENT ON COLUMN SMS_TEMPLATE.ID IS '数据ID';

COMMENT ON COLUMN SMS_TEMPLATE.CONTENT IS '内容';

COMMENT ON COLUMN SMS_TEMPLATE.TYPE IS '短信类型';

COMMENT ON COLUMN SMS_TEMPLATE.PARAMS_NUM IS '参数个数';

COMMENT ON COLUMN SMS_TEMPLATE.STATUS IS '状态1启用0停用';

COMMENT ON COLUMN SMS_TEMPLATE.REMARK IS '备注';

COMMENT ON COLUMN SMS_TEMPLATE.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN SMS_TEMPLATE.CREATED_USER_ID IS '创建人ID';

COMMENT ON COLUMN SMS_TEMPLATE.UPDATED_TIME IS '修改时间';

COMMENT ON COLUMN SMS_TEMPLATE.UPDATED_USER_ID IS '修改人ID';



CREATE UNIQUE INDEX PK_SMS_TEMPLATE ON SMS_TEMPLATE
(ID);


ALTER TABLE SMS_TEMPLATE ADD (
  CONSTRAINT PK_SMS_TEMPLATE
  PRIMARY KEY
  (ID)
  USING INDEX PK_SMS_TEMPLATE
  ENABLE VALIDATE);
