CREATE TABLE T_BATCH_LOG
(
  ID              NUMBER(10)                    NOT NULL,
  BAT_NAME        VARCHAR2(200 BYTE),
  BAT_STATUS      VARCHAR2(2 BYTE),
  BAT_START_TIME  DATE,
  BAT_END_TIME    DATE,
  REMARK          VARCHAR2(1000 BYTE),
  CREATE_DATE     DATE
);

COMMENT ON COLUMN T_BATCH_LOG.ID IS '数据ID';

COMMENT ON COLUMN T_BATCH_LOG.BAT_NAME IS '批处理名称';

COMMENT ON COLUMN T_BATCH_LOG.BAT_STATUS IS '批处理状态 0:失败  1:成功';

COMMENT ON COLUMN T_BATCH_LOG.BAT_START_TIME IS '开始时间';

COMMENT ON COLUMN T_BATCH_LOG.BAT_END_TIME IS '结束时间';

COMMENT ON COLUMN T_BATCH_LOG.REMARK IS '描述';

COMMENT ON COLUMN T_BATCH_LOG.CREATE_DATE IS '创建时间';



CREATE UNIQUE INDEX PK_T_BATCH_LOG ON T_BATCH_LOG
(ID);


ALTER TABLE T_BATCH_LOG ADD (
  CONSTRAINT PK_T_BATCH_LOG
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_BATCH_LOG
  ENABLE VALIDATE);
