CREATE TABLE T_COUPON_INFO
(
  ID               NUMBER(10)                   NOT NULL,
  COUPON_TYPE_ID   NUMBER(10),
  PARTNER_ID       NUMBER(10),
  COUPON_CODE      VARCHAR2(20 BYTE),
  VALUE            NUMBER(8,2),
  START_DATE       DATE,
  END_DATE         DATE,
  STATUS           VARCHAR2(5 BYTE),
  CREATED_TIME     DATE                         DEFAULT SYSDATE,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE                         DEFAULT SYSDATE,
  UPDATED_USER_ID  NUMBER(10),
  REMARK           VARCHAR2(100 BYTE),
  IS_MATCH         VARCHAR2(5 BYTE)             DEFAULT '0'
);

COMMENT ON TABLE T_COUPON_INFO IS '赠券信息';

COMMENT ON COLUMN T_COUPON_INFO.ID IS '数据ID';

COMMENT ON COLUMN T_COUPON_INFO.COUPON_TYPE_ID IS '赠券类型ID';

COMMENT ON COLUMN T_COUPON_INFO.PARTNER_ID IS '合作商ID';

COMMENT ON COLUMN T_COUPON_INFO.COUPON_CODE IS '赠券码';

COMMENT ON COLUMN T_COUPON_INFO.VALUE IS '面值';

COMMENT ON COLUMN T_COUPON_INFO.START_DATE IS '开始日期';

COMMENT ON COLUMN T_COUPON_INFO.END_DATE IS '结束日期';

COMMENT ON COLUMN T_COUPON_INFO.STATUS IS '状态';

COMMENT ON COLUMN T_COUPON_INFO.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN T_COUPON_INFO.CREATED_USER_ID IS '创建人ID';

COMMENT ON COLUMN T_COUPON_INFO.UPDATED_TIME IS '更新时间';

COMMENT ON COLUMN T_COUPON_INFO.UPDATED_USER_ID IS '更新人ID';

COMMENT ON COLUMN T_COUPON_INFO.REMARK IS '备注';

COMMENT ON COLUMN T_COUPON_INFO.IS_MATCH IS '是否匹配用户';



CREATE UNIQUE INDEX PK_T_COUPON_INFO ON T_COUPON_INFO
(ID);


ALTER TABLE T_COUPON_INFO ADD (
  CONSTRAINT PK_T_COUPON_INFO
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_COUPON_INFO
  ENABLE VALIDATE);
