CREATE TABLE T_COUPON_CLIENT
(
  ID               NUMBER(10)                   NOT NULL,
  CLIENT_NAME      VARCHAR2(50 BYTE),
  CLIENT_TEL       VARCHAR2(20 BYTE),
  PARTNER_CODE     VARCHAR2(20 BYTE),
  PRODUCT          VARCHAR2(100 BYTE),
  COUPON_ID        NUMBER(10),
  STATUS           VARCHAR2(5 BYTE),
  SEND_DATE        DATE,
  USE_DATE         DATE,
  CREATED_TIME     DATE                         DEFAULT SYSDATE,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE                         DEFAULT SYSDATE,
  UPDATED_USER_ID  NUMBER(10),
  REMARK           VARCHAR2(100 BYTE)
);

COMMENT ON TABLE T_COUPON_CLIENT IS '客户券信息';

COMMENT ON COLUMN T_COUPON_CLIENT.ID IS '数据ID';

COMMENT ON COLUMN T_COUPON_CLIENT.CLIENT_NAME IS '用户姓名';

COMMENT ON COLUMN T_COUPON_CLIENT.CLIENT_TEL IS '用户电话';

COMMENT ON COLUMN T_COUPON_CLIENT.PARTNER_CODE IS '合作商编号';

COMMENT ON COLUMN T_COUPON_CLIENT.PRODUCT IS '购买产品';

COMMENT ON COLUMN T_COUPON_CLIENT.COUPON_ID IS '赠券ID';

COMMENT ON COLUMN T_COUPON_CLIENT.STATUS IS '状态';

COMMENT ON COLUMN T_COUPON_CLIENT.SEND_DATE IS '发放日期';

COMMENT ON COLUMN T_COUPON_CLIENT.USE_DATE IS '使用日期';

COMMENT ON COLUMN T_COUPON_CLIENT.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN T_COUPON_CLIENT.CREATED_USER_ID IS '创建人ID';

COMMENT ON COLUMN T_COUPON_CLIENT.UPDATED_TIME IS '更新时间';

COMMENT ON COLUMN T_COUPON_CLIENT.UPDATED_USER_ID IS '更新人ID';

COMMENT ON COLUMN T_COUPON_CLIENT.REMARK IS '备注';



CREATE UNIQUE INDEX PK_T_COUPON_CLIENT ON T_COUPON_CLIENT
(ID);


ALTER TABLE T_COUPON_CLIENT ADD (
  CONSTRAINT PK_T_COUPON_CLIENT
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_COUPON_CLIENT
  ENABLE VALIDATE);
