CREATE TABLE T_COUPON_TYPE
(
  ID               NUMBER(10)                   NOT NULL,
  PARTNER_ID       NUMBER(10),
  COUPON_TYPE      VARCHAR2(5 BYTE),
  COUPON_NAME      VARCHAR2(50 BYTE),
  STATUS           VARCHAR2(5 BYTE),
  CREATED_TIME     DATE                         DEFAULT SYSDATE,
  CREATED_USER_ID  NUMBER(10),
  UPDATED_TIME     DATE                         DEFAULT SYSDATE,
  UPDATED_USER_ID  NUMBER(10),
  REMARK           VARCHAR2(100 BYTE)
);

COMMENT ON TABLE T_COUPON_TYPE IS '赠券类型';

COMMENT ON COLUMN T_COUPON_TYPE.ID IS '数据ID';

COMMENT ON COLUMN T_COUPON_TYPE.PARTNER_ID IS '合作商ID';

COMMENT ON COLUMN T_COUPON_TYPE.COUPON_TYPE IS '赠券类型';

COMMENT ON COLUMN T_COUPON_TYPE.COUPON_NAME IS '赠券名称';

COMMENT ON COLUMN T_COUPON_TYPE.STATUS IS '状态';

COMMENT ON COLUMN T_COUPON_TYPE.CREATED_TIME IS '创建时间';

COMMENT ON COLUMN T_COUPON_TYPE.CREATED_USER_ID IS '创建人ID';

COMMENT ON COLUMN T_COUPON_TYPE.UPDATED_TIME IS '更新时间';

COMMENT ON COLUMN T_COUPON_TYPE.UPDATED_USER_ID IS '更新人ID';

COMMENT ON COLUMN T_COUPON_TYPE.REMARK IS '备注';



CREATE UNIQUE INDEX PK_T_COUPON_TYPE ON T_COUPON_TYPE
(ID);


ALTER TABLE T_COUPON_TYPE ADD (
  CONSTRAINT PK_T_COUPON_TYPE
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_COUPON_TYPE
  ENABLE VALIDATE);
