CREATE TABLE T_MODULE_URL
(
  MODULE_ID    NUMBER(10)                       NOT NULL,
  MODULE_NAME  VARCHAR2(500 BYTE)               NOT NULL,
  MODULE_URL   VARCHAR2(500 BYTE)               NOT NULL,
  REMARK       VARCHAR2(500 BYTE),
  CREATE_DATE  DATE                             DEFAULT sysdate
);

COMMENT ON TABLE T_MODULE_URL IS '²Ëµ¥url';



CREATE UNIQUE INDEX PK_MODULE_URL_ID ON T_MODULE_URL
(MODULE_ID);


ALTER TABLE T_MODULE_URL ADD (
  CONSTRAINT PK_MODULE_URL_ID
  PRIMARY KEY
  (MODULE_ID)
  USING INDEX PK_MODULE_URL_ID
  ENABLE VALIDATE);
