CREATE TABLE T_ORGAN_COMPANY_PRO
(
  ORGAN_ID     VARCHAR2(10 BYTE)                NOT NULL,
  PARENT_ID    VARCHAR2(10 BYTE),
  NAME         VARCHAR2(200 BYTE),
  ABBR_NAME    VARCHAR2(200 BYTE),
  ADDRESS      VARCHAR2(500 BYTE),
  STATUS       VARCHAR2(2 BYTE),
  CREATE_DATE  DATE,
  ORGAN_CODE   VARCHAR2(20 BYTE)                NOT NULL
);
