CREATE TABLE T_ORGAN
(
  ID           NUMBER(5)                        NOT NULL,
  ORGAN_NAME   VARCHAR2(200 BYTE),
  ORGAN_CODE   VARCHAR2(20 BYTE),
  CREATE_DATE  DATE                             DEFAULT sysdate
);

COMMENT ON TABLE T_ORGAN IS '组织';

COMMENT ON COLUMN T_ORGAN.ORGAN_NAME IS '名称';

COMMENT ON COLUMN T_ORGAN.ORGAN_CODE IS '代码';



CREATE UNIQUE INDEX T_ORGAN_PK ON T_ORGAN
(ID);


ALTER TABLE T_ORGAN ADD (
  CONSTRAINT T_ORGAN_PK
  PRIMARY KEY
  (ID)
  USING INDEX T_ORGAN_PK
  ENABLE VALIDATE);
