CREATE TABLE T_ROLE
(
  ID           NUMBER(10)                       NOT NULL,
  ROLE_NAME    VARCHAR2(100 BYTE),
  STATUS       VARCHAR2(2 BYTE)                 DEFAULT 1,
  CREATE_DATE  DATE                             DEFAULT sysdate
);


CREATE UNIQUE INDEX PK_USER_ROLE_ID ON T_ROLE
(ID);


ALTER TABLE T_ROLE ADD (
  CONSTRAINT PK_USER_ROLE_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_USER_ROLE_ID
  ENABLE VALIDATE);
