CREATE TABLE T_SYSVAR
(
  ID            NUMBER(10)                      NOT NULL,
  SYSVAR_CODE   VARCHAR2(50 BYTE),
  SYSVAR_NAME   VARCHAR2(50 BYTE),
  SYSVAR_VALUE  VARCHAR2(200 BYTE),
  SYSVAR_TYPE   VARCHAR2(50 BYTE)
);

COMMENT ON TABLE T_SYSVAR IS '系统变量表';

COMMENT ON COLUMN T_SYSVAR.ID IS '数据ID';

COMMENT ON COLUMN T_SYSVAR.SYSVAR_CODE IS '变量编码';

COMMENT ON COLUMN T_SYSVAR.SYSVAR_NAME IS '变量名称';

COMMENT ON COLUMN T_SYSVAR.SYSVAR_VALUE IS '变量值';

COMMENT ON COLUMN T_SYSVAR.SYSVAR_TYPE IS '变量类型';



CREATE UNIQUE INDEX PK_T_SYSVAR ON T_SYSVAR
(ID);


ALTER TABLE T_SYSVAR ADD (
  CONSTRAINT PK_T_SYSVAR
  PRIMARY KEY
  (ID)
  USING INDEX PK_T_SYSVAR
  ENABLE VALIDATE);
