CREATE TABLE T_USER_ROLE
(
  USER_ID  NUMBER(10),
  ROLE_ID  NUMBER(10)
);


ALTER TABLE T_USER_ROLE ADD (
  CONSTRAINT FK_USER_ROLE_ROLE_ID 
  FOREIGN KEY (ROLE_ID) 
  REFERENCES T_ROLE (ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_USER_ROLE_USER_ID 
  FOREIGN KEY (USER_ID) 
  REFERENCES T_USER (USER_ID)
  ENABLE VALIDATE);
