CREATE TABLE T_USER_GROUP
(
  USER_ID   NUMBER(10)                          NOT NULL,
  GROUP_ID  NUMBER(10)                          NOT NULL
);

COMMENT ON TABLE T_USER_GROUP IS '用户菜单组';



ALTER TABLE T_USER_GROUP ADD (
  CONSTRAINT FK_USER_GROUP_GROUP_ID 
  FOREIGN KEY (GROUP_ID) 
  REFERENCES T_MODULE_GROUP (GROUP_ID)
  ENABLE VALIDATE);
