CREATE TABLE T_WEIXIN_APPS
(
  ID                NUMBER(10)                  NOT NULL,
  MAIN_ID           NUMBER(10)                  NOT NULL,
  APP_ID            NUMBER(10),
  APP_NAME          VARCHAR2(100 BYTE)          NOT NULL,
  TOKEN             VARCHAR2(400 BYTE)          NOT NULL,
  ENCODING_AES_KEY  VARCHAR2(400 BYTE)          NOT NULL,
  CALL_BACK_URL     VARCHAR2(400 BYTE)          NOT NULL,
  SECRET            VARCHAR2(400 BYTE),
  CREATE_DATE       DATE                        DEFAULT sysdate,
  ACCECC_TOKEN      VARCHAR2(400 BYTE),
  ACCESS_TICKET     VARCHAR2(400 BYTE)
);

COMMENT ON TABLE T_WEIXIN_APPS IS '企业号小应用';

COMMENT ON COLUMN T_WEIXIN_APPS.MAIN_ID IS '主表ID';

COMMENT ON COLUMN T_WEIXIN_APPS.APP_ID IS '应用id';

COMMENT ON COLUMN T_WEIXIN_APPS.APP_NAME IS '应用名称';

COMMENT ON COLUMN T_WEIXIN_APPS.TOKEN IS 'token';

COMMENT ON COLUMN T_WEIXIN_APPS.ENCODING_AES_KEY IS '加密串';

COMMENT ON COLUMN T_WEIXIN_APPS.CALL_BACK_URL IS '回调url';

COMMENT ON COLUMN T_WEIXIN_APPS.SECRET IS 'Secret';

COMMENT ON COLUMN T_WEIXIN_APPS.ACCECC_TOKEN IS 'token';

COMMENT ON COLUMN T_WEIXIN_APPS.ACCESS_TICKET IS 'ticket';



CREATE UNIQUE INDEX PK_WEIXIN_APPS_ID ON T_WEIXIN_APPS
(ID);


ALTER TABLE T_WEIXIN_APPS ADD (
  CONSTRAINT PK_WEIXIN_APPS_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_WEIXIN_APPS_ID
  ENABLE VALIDATE);

ALTER TABLE T_WEIXIN_APPS ADD (
  CONSTRAINT FK_WEIXIN_MAIN_ID 
  FOREIGN KEY (MAIN_ID) 
  REFERENCES T_WEIXIN_MAIN (ID)
  ENABLE VALIDATE);
